---
- hosts: leafs,spines
  tasks:
    - name: configure lldpd settings to only listen on non-mgmt ports
      blockinfile:
        dest: /etc/lldp.d/README.conf
        insertafter: EOF
      block: |
        configure system interface pattern eth*,swp*,!eth0
      become: yes
    - service:
        name: lldpd
        state: restarted
       become: true


- hosts: servers
  tasks:
    - name: configure lldpd settings to only listen on non-mgmt ports
       blockinfile:
         dest: /etc/lldp.d/README.conf
         insertafter: EOF
         block: |
           configure system interface pattern eth*,!eth0
           configure lldp portidsubtype ifname
       become: yes

- hosts: server02,server03,server04
  roles:
    - add custom docker network
