- name: configure lldpd settings to only listen on non-mgmt ports
   blockinfile:
     dest: /etc/lldp.d/README.conf
     insertafter: EOF
     block: |
       configure system interface pattern eth*,!eth0
       configure lldp portidsubtype ifname
   become: yes